### ISSUE TITLE
Missing sub-module `measurements` in v0.4.0

### ISSUE THREAD

**Issue by ccoulombe** [calculquebec/pennylane-snowflurry#22]
```
$ python -c 'import pennylane_snowflurry'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/coulombc/30091/lib/python3.11/site-packages/pennylane_snowflurry/__init__.py", line 5, in <module>
    from .pennylane_converter import PennylaneConverter
  File "/tmp/coulombc/30091/lib/python3.11/site-packages/pennylane_snowflurry/pennylane_converter.py", line 21, in <module>
    from pennylane_snowflurry.measurements import (
ModuleNotFoundError: No module named 'pennylane_snowflurry.measurements'
```

The sdists on PyPI is missing the `measurements` sub-module.
The release on GH does contain it though.

**Comment by ccoulombe** [comment]
Idem for the [wheel on PyPI](https://files.pythonhosted.org/packages/aa/a1/4435451e2680b55ba3b2e2b6478cc38117e573d3059fe2b0463dfdcffd48/pennylane_snowflurry-0.4.0-py3-none-any.whl)

```
$ unzip -v pennylane_snowflurry-0.4.0-py3-none-any.whl | fgrep meas
$ 
```
